[connections.my_example_connection]
account = "WBLAEAY-YJB21421"
user = "MARCUSMORGENSTIERNE77"
password= "SommerFerie2027"
role = "SYSADMIN"
warehouse = "COMPUTEWH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true 
